<!DOCTYPE html>
<html lang="en">
<head>
<title>The Runner  | Amateur Baseball Federation of India | THE OFFICIAL SITE OF INDIAN BASEBALL</title>
	<?php include('includes/header.php');?>	
</head>
<body>
<div id="outer_m">
	<?php include('includes/nav.php');?>
<div id="main">

<div id="stickleft">
<i class="fa fa-facebook-square" style="font-size:32px; margin-left:2px; cursor:pointer; color:#2d3e50;"></i>
<i class="fa fa-youtube-square" style="font-size:32px; margin-left:2px; cursor:pointer;  color:#2d3e50;"></i>
<i class="fa fa-twitter-square" style="font-size:32px; margin-left:2px; cursor:pointer; color:#2d3e50;"></i>
<i class="fa fa-linkedin-square" style="font-size:32px; margin-left:2px; cursor:pointer; color:#2d3e50;"></i>
</div>


<a href="rules.html"><div id="stick_right"></div></a>

<div id="basic">

<div id="keep3">
<h3 class="heading3070">7.00 The Runner</h3>
<p class="depart_p">

                            
                            <strong>7.01</strong><br />
                      A runner acquires the right to an unoccupied base when he touches it  before he is out. He is then entitled to it until he is put out, or  forced to vacate it for another runner legally entitled to that base.  If a runner legally acquires title to a base, and the pitcher assumes  his pitching position, the runner may not return to a previously  occupied base.<br />
                      <br />
                      <strong>7.02</strong><br />
                      In advancing, a runner shall touch first, second, third and home base  in order. If forced to return, he shall retouch all bases in reverse  order, unless the ball is dead under any provision of Rule 5.09. In  such cases, the runner may go directly to his original base.<br />
                      <br />
                      <strong>7.03</strong><br />
                      Two runners may not occupy a base, but if, while the ball is alive, two  runners are touching a base, the following runner shall be out when  tagged. The preceding runner is entitled to the base.<br />
                      <br />
                      <strong>7.04</strong><br />
                      Each runner, other than the batter, may without liability to be put out, advance one base when_ <br />
                      <br />
                      (a) There is a balk;<br />
                      (b) The batter's advance without  liability to be put out forces the runner to vacate his base, or when  the batter hits a fair ball that touches another runner or the umpire  before such ball has been touched by, or has passed a fielder, if the  runner is forced to advance; A runner forced to advance without  liability to be put out may advance past the base to which he is  entitled only at his peril. If such a runner, forced to advance, is put  out for the third out before a preceding runner, also forced to  advance, touches home plate, the run shall score. Play. Two out, bases  full, batter walks but runner from second is overzealous and runs past  third base toward home and is tagged out on a throw by the catcher.  Even though two are out, the run would score on the theory that the run  was forced home by the base on balls and that all the runners needed to  do was proceed and touch the next base. <br />
                      (c) A fielder, after catching a fly ball, falls into a bench or stand,  or falls across ropes into a crowd when spectators are on the field; A  fielder or catcher may reach or step into, or go into the dugout with  one or both feet to make a catch, and if he holds the ball, the catch  shall be allowed. Ball is in play. If the fielder or catcher, after  having made a legal catch, should fall into a stand or among spectators  or into the dugout after making a legal catch, or fall while in the  dugout after making a legal catch, the ball is dead and runners advance  one base without liability to be put out.<br />
                      (d) While he is attempting to steal a base, the batter is interfered  with by the catcher or any other fielder. NOTE: When a runner is  entitled to a base without liability to be put out, while the ball is  in play, or under any rule in which the ball is in play after the  runner reaches the base to which he is entitled, and the runner fails  to touch the base to which he is entitled before attempting to advance  to the next base, the runner shall forfeit his exemption from liability  to be put out, and he may be put out by tagging the base or by tagging  the runner before he returns to the missed base.<br />
                      <br />
                      <strong>7.05</strong><br />
                      Each runner including the batter runner may, without liability to be put out, advance_<br />
                      <br />
                      (a) To home base, scoring a run, if a fair ball goes out of the playing  field in flight and he touched all bases legally; or if a fair ball  which, in the umpire's judgment, would have gone out of the playing  field in flight, is deflected by the act of a fielder in throwing his  glove, cap, or any article of his apparel;<br />
                      (b) Three bases, if a fielder deliberately touches a fair ball with his  cap, mask or any part of his uniform detached from its proper place on  his person. The ball is in play and the batter may advance to home base  at his peril; <br />
                      (c) Three bases, if a fielder deliberately throws his glove at and  touches a fair ball. The ball is in play and the batter may advance to  home base at his peril.<br />
                      (d) Two bases, if a fielder deliberately touches a thrown ball with his  cap, mask or any part of his uniform detached from its proper place on  his person. The ball is in play;<br />
                      (e) Two bases, if a fielder deliberately throws his glove at and  touches a thrown ball. The ball is in play; In applying (b c d e) the  umpire must rule that the thrown glove or detached cap or mask has  touched the ball. There is no penalty if the ball is not touched. Under  (c e) this penalty shall not be invoked against a fielder whose glove  is carried off his hand by the force of a batted or thrown ball, or  when his glove flies off his hand as he makes an obvious effort to make  a legitimate catch. <br />
                      (f) Two bases, if a fair ball bounces or is deflected into the stands  outside the first or third base foul lines; or if it goes through or  under a field fence, or through or under a scoreboard, or through or  under shrubbery or vines on the fence; or if it sticks in such fence,  scoreboard, shrubbery or vines; <br />
                      (g) Two bases when, with no spectators on the playing field, a thrown  ball goes into the stands, or into a bench (whether or not the ball  rebounds into the field), or over or under or through a field fence, or  on a slanting part of the screen above the backstop, or remains in the  meshes of a wire screen protecting spectators. The ball is dead. When  such wild throw is the first play by an infielder, the umpire, in  awarding such bases, shall be governed by the position of the runners  at the time the ball was pitched; in all other cases the umpire shall  be governed by the position of the runners at the time the wild throw  was made; <br />
                      <br />
                      <strong>APPROVED RULING:</strong> If all runners, including the batter  runner, have advanced at least one base when an infielder makes a wild  throw on the first play after the pitch, the award shall be governed by  the position of the runners when the wild throw was made. In certain  circumstances it is impossible to award a runner two bases. Example:  Runner on first. Batter hits fly to short right. Runner holds up  between first and second and batter comes around first and pulls up  behind him. Ball falls safely. Outfielder, in throwing to first, throws  ball into stand. APPROVED RULING: Since no runner, when the ball is  dead, may advance beyond the base to which he is entitled, the runner  originally on first base goes to third base and the batter is held at  second base. The term &quot;when the wild throw was made&quot; means when the  throw actually left the player's hand and not when the thrown ball hit  the ground, passes a receiving fielder or goes out of play into the  stands. The position of the batter runner at the time the wild throw  left the thrower's hand is the key in deciding the award of bases. If  the batter runner has not reached first base, the award is two bases at  the time the pitch was made for all runners. The decision as to whether  the batter runner has reached first base before the throw is a judgment  call. If an unusual play arises where a first throw by an infielder  goes into stands or dugout but the batter did not become a runner (such  as catcher throwing ball into stands in attempt to get runner from  third trying to score on passed ball or wild pitch) award of two bases  shall be from the position of the runners at the time of the throw.  (For the purpose of Rule <br />
                      <br />
                      <strong>7.05 </strong><br />
                      (g) a catcher is considered an infielder.) PLAY. Runner on first base,  batter hits a ball to the shortstop, who throws to second base too late  to get runner at second, and second baseman throws toward first base  after batter has crossed first base. Ruling Runner at second scores.  (On this play, only if batter runner is past first base when throw is  made is he awarded third base.)<br />
                      (h) One base, if a ball, pitched to the batter, or thrown by the  pitcher from his position on the pitcher's plate to a base to catch a  runner, goes into a stand or a bench, or over or through a field fence  or backstop. The ball is dead;<br />
                      <br />
                      <strong>APPROVED RULING: </strong>When a wild pitch or passed ball goes  through or by the catcher, or deflects off the catcher, and goes  directly into the dugout, stands, above the break, or any area where  the ball is dead, the awarding of bases shall be one base. One base  shall also be awarded if the pitcher while in contact with the rubber,  throws to a base, and the throw goes directly into the stands or into  any area where the ball is dead. If, however, the pitched or thrown  ball goes through or by the catcher or through the fielder, and remains  on the playing field, and is subsequently kicked or deflected into the  dugout, stands or other area where the ball is dead, the awarding of  bases shall be two bases from position of runners at the time of the  pitch or throw. <br />
                      <br />
                      (i) One base, if the batter becomes a runner on Ball Four or Strike  Three, when the pitch passes the catcher and lodges in the umpire's  mask or paraphernalia. If the batter becomes a runner on a wild pitch  which entitles the runners to advance one base, the batter runner shall  be entitled to first base only. The fact a runner is awarded a base or  bases without liability to be put out does not relieve him of the  responsibility to touch the base he is awarded and all intervening  bases. For example: batter hits a ground ball which an infielder throws  into the stands but the batter runner missed first base. He may be  called out on appeal for missing first base after the ball is put in  play even though he was &quot;awarded&quot; second base. If a runner is forced to  return to a base after a catch, he must retouch his original base even  though, because of some ground rule or other rule, he is awarded  additional bases. He may retouch while the ball is dead and the award  is then made from his original base.<br />
                      <br />
                      <strong>7.06</strong><br />
                      When obstruction occurs, the umpire shall call or signal &quot;Obstruction.&quot;<br />
                      <br />
                      (a) If a play is being made on the obstructed runner, or if the  batter runner is obstructed before he touches first base, the ball is  dead and all runners shall advance, without liability to be put out, to  the bases they would have reached, in the umpire's judgment, if there  had been no obstruction. The obstructed runner shall be awarded at  least one base beyond the base he had last legally touched before the  obstruction. Any preceding runners, forced to advance by the award of  bases as the penalty for obstruction, shall advance without liability  to be put out. When a play is being made on an obstructed runner, the  umpire shall signal obstruction in the same manner that he calls  &quot;Time,&quot; with both hands overhead. The ball is immediately dead when  this signal is given; however, should a thrown ball be in flight before  the obstruction is called by the umpire, the runners are to be awarded  such bases on wild throws as they would have been awarded had not  obstruction occurred. On a play where a runner was trapped between  second and third and obstructed by the third baseman going into third  base while the throw is in flight from the shortstop, if such throw  goes into the dugout the obstructed runner is to be awarded home base.  Any other runners on base in this situation would also be awarded two  bases from the base they last legally touched before obstruction was  called. <br />
                      (b) If no play is being made on the obstructed runner, the play shall  proceed until no further action is possible. The umpire shall then call  &quot;Time&quot; and impose such penalties, if any, as in his judgment will  nullify the act of obstruction. Under 7.06 (b) when the ball is not  dead on obstruction and an obstructed runner advances beyond the base  which, in the umpire's judgment, he would have been awarded because of  being obstructed, he does so at his own peril and may be tagged out.  This is a judgment call. <br />
                      <br />
                      <strong>NOTE: </strong>The catcher, without the ball in his possession,  has no right to block the pathway of the runner attempting to score.  The base line belongs to the runner and the catcher should be there  only when he is fielding a ball or when he already has the ball in his  hand.  7.07  If, with a runner on third base and trying to score by means of a  squeeze play or a steal, the catcher or any other fielder steps on, or  in front of home base without possession of the ball, or touches the  batter or his bat, the pitcher shall be charged with a balk, the batter  shall be awarded first base on the interference and the ball is dead.<br />
                      <br />
                      <strong>7.08</strong><br />
                      <br />
                      Any runner is out when_<br />
                      <br />
                      (a) (1) He runs more than three feet away from a direct line  between bases to avoid being tagged unless his action is to avoid  interference with a fielder fielding a batted ball; or<br />
                      (2) after touching first base, he leaves the baseline, obviously  abandoning his effort to touch the next base; Any runner after reaching  first base who leaves the baseline heading for his dugout or his  position believing that there is no further play, may be declared out  if the umpire judges the act of the runner to be considered abandoning  his efforts to run the bases. Even though an out is called, the ball  remains in play in regard to any other runner. This rule also covers  the following and similar plays: Less than two out, score tied last of  ninth inning, runner on first, batter hits a ball out of park for  winning run, the runner on first passes second and thinking the home  run automatically wins the game, cuts across diamond toward his bench  as batter runner circles bases. In this case, the base runner would be  called out &quot;for abandoning his effort to touch the next base&quot; and  batter runner permitted to continue around bases to make his home run  valid. If there are two out, home run would not count (see Rule 7.12).  This is not an appeal play.<br />
                      PLAY. Runner believing he is called out on a tag at first or third base  starts for the dugout and progresses a reasonable distance still  indicating by his actions that he is out, shall be declared out for  abandoning the bases. In the above two plays the runners are considered  actually abandoning their base paths and are treated differently than  the batter who struck out as described. APPROVED RULING OF 7.08 <br />
                      (a). <strong>APPROVED RULING:</strong> When a batter becomes a runner on  third strike not caught, and starts for his bench or position, he may  advance to first base at any time before he enters the bench. To put  him out, the defense must tag him or first base before he touches first  base. <br />
                      (b) He intentionally interferes with a thrown ball; or hinders a  fielder attempting to make a play on a batted ball; A runner who is  adjudged to have hindered a fielder who is attempting to make a play on  a batted ball is out whether it was intentional or not. If, however,  the runner has contact with a legally occupied base when he hinders the  fielder, he shall not be called out unless, in the umpire's judgment,  such hindrance, whether it occurs on fair or foul territory, is  intentional. If the umpire declares the hindrance intentional, the  following penalty shall apply: With less than two out, the umpire shall  declare both the runner and batter out. With two out, the umpire shall  declare the batter out. If, in a run down between third base and home  plate, the succeeding runner has advanced and is standing on third base  when the runner in a run down is called out for offensive interference,  the umpire shall send the runner standing on third base back to second  base. This same principle applies if there is a run down between second  and third base and succeeding runner has reached second (the reasoning  is that no runner shall advance on an interference play and a runner is  considered to occupy a base until he legally has reached the next  succeeding base). <br />
                      (c) He is tagged, when the ball is alive, while off his base. <br />
                      <strong>EXCEPTION:</strong> A batter runner cannot be tagged out after overrunning or oversliding first base if he returns immediately to the base;<br />
                      <br />
                      <strong>APPROVED RULING:   (1)</strong> If the impact of a runner  breaks a base loose from its position, no play can be made on that  runner at that base if he had reached the base safely.<br />
                      <strong>APPROVED RULING: (2)</strong> If a base is dislodged from its  position during a play, any following runner on the same play shall be  considered as touching or occupying the base if, in the umpire's  judgment, he touches or occupies the point marked by the dislodged bag.<br />
                      <br />
                      (d) He fails to retouch his base after a fair or foul ball is  legally caught before he, or his base, is tagged by a fielder. He shall  not be called out for failure to retouch his base after the first  following pitch, or any play or attempted play. This is an appeal play;  Runners need not &quot;tag up&quot; on a foul tip. They may steal on a foul tip.  If a so called tip is not caught, it becomes an ordinary foul. Runners  then return to their bases. <br />
                      (e) He fails to reach the next base before a fielder tags him or the  base, after he has been forced to advance by reason of the batter  becoming a runner. However, if a following runner is put out on a force  play, the force is removed and the runner must be tagged to be put out.  The force is removed as soon as the runner touches the base to which he  is forced to advance, and if he overslides or overruns the base, the  runner must be tagged to be put out. However, if the forced runner,  after touching the next base, retreats for any reason towards the base  he had last occupied, the force play is reinstated, and he can again be  put out if the defense tags the base to which he is forced; PLAY.  Runner on first and three balls on batter: Runner steals on the next  pitch, which is fourth ball, but after having touched second he  overslides or overruns that base. Catcher's throw catches him before he  can return. Ruling is that runner is out. (Force out is removed.)  Oversliding and overrunning situations arise at bases other than first  base. For instance, before two are out, and runners on first and  second, or first, second and third, the ball is hit to an infielder who  tries for the double play. The runner on first beats the throw to  second base but overslides the base. The relay is made to first base  and the batter runner is out. The first baseman, seeing the runner at  second base off the bag, makes the return throw to second and the  runner is tagged off the base. Meanwhile runners have crossed the  plate. The question is: Is this a force play? Was the force removed  when the batter runner was out at first base? Do the runs that crossed  the plate during this play and before the third out was made when the  runner was tagged at second, count? Answer: The runs score. It is not a  force play. It is a tag play. <br />
                      (f) He is touched by a fair ball in fair territory before the ball has  touched or passed an infielder. The ball is dead and no runner may  score, nor runners advance, except runners forced to advance. <br />
                      <br />
                      <strong>EXCEPTION:</strong> If a runner is touching his base when  touched by an Infield Fly, he is not out, although the batter is out;  If two runners are touched by the same fair ball, only the first one is  out because the ball is instantly dead. If runner is touched by an  Infield Fly when he is not touching his base, both runner and batter  are out.<br />
                      <br />
                      (g) He attempts to score on a play in which the batter interferes  with the play at home base before two are out. With two out, the  interference puts the batter out and no score counts;<br />
                      (h) He passes a preceding runner before such runner is out; <br />
                      (i) After he has acquired legal possession of a base, he runs the bases  in reverse order for the purpose of confusing the defense or making a  travesty of the game. The umpire shall immediately call &quot;Time&quot; and  declare the runner out; If a runner touches an unoccupied base and then  thinks the ball was caught or is decoyed into returning to the base he  last touched, he may be put out running back to that base, but if he  reaches the previously occupied base safely he cannot be put out while  in contact with that base. <br />
                      (j) He fails to return at once to first base after overrunning or  oversliding that base. If he attempts to run to second he is out when  tagged. If, after overrunning or oversliding first base he starts  toward the dugout, or toward his position, and fails to return to first  base at once, he is out, on appeal, when he or the base is tagged;  Runner who touches first base in overrunning and is declared safe by  the umpire has, within the intent of Rule 4.09 (a) &quot;reached first base&quot;  and any run which scores on such a play counts, even though the runner  subsequently becomes the third out for failure to return &quot;at once,&quot; as  covered in Rule 7.08 (j).<br />
                      (k) In running or sliding for home base, he fails to touch home base  and makes no attempt to return to the base, when a fielder holds the  ball in his hand, while touching home base, and appeals to the umpire  for the decision. This rule applies only where runner is on his way to  the bench and the catcher would be required to chase him. It does not  apply to the ordinary play where the runner misses the plate and then  immediately makes an effort to touch the plate before being tagged. In  that case, runner must be tagged.<br />
                      <br />
                      <strong>7.09 </strong><br />
                      It is interference by a batter or a runner when: <br />
                      (a) After a third strike he hinders the catcher in his attempt to field the ball;<br />
                      (b) After hitting or bunting a fair ball, his bat hits the ball a  second time in fair territory. The ball is dead and no runners may  advance. If the batter runner drops his bat and the ball rolls against  the bat in fair territory and, in the umpire's judgment, there was no  intention to interfere with the course of the ball, the ball is alive  and in play; <br />
                      (c) He intentionally deflects the course of a foul ball in any manner;<br />
                      (d) Before two are out and a runner on third base, the batter hinders a  fielder in making a play at home base; the runner is out; <br />
                      (e) Any member or members of the offensive team stand or gather around  any base to which a runner is advancing, to confuse, hinder or add to  the difficulty of the fielders. Such runner shall be declared out for  the interference of his teammate or teammates; <br />
                      (f) Any batter or runner who has just been put out hinders or impedes  any following play being made on a runner. Such runner shall be  declared out for the interference of his teammate; If the batter or a  runner continues to advance after he has been put out, he shall not by  that act alone be considered as confusing, hindering or impeding the  fielders.<br />
                      (g) If, in the judgment of the umpire, a base runner willfully and  deliberately interferes with a batted ball or a fielder in the act of  fielding a batted ball with the obvious intent to break up a double  play, the ball is dead. The umpire shall call the runner out for  interference and also call out the batter runner because of the action  of his teammate. In no event may bases be run or runs scored because of  such action by a runner. <br />
                      (h) If, in the judgment of the umpire, a batter runner willfully and  deliberately interferes with a batted ball or a fielder in the act of  fielding a batted ball, with the obvious intent to break up a double  play, the ball is dead; the umpire shall call the batter runner out for  interference and shall also call out the runner who had advanced  closest to the home plate regardless where the double play might have  been possible. In no event shall bases be run because of such  interference. <br />
                      (i) In the judgment of the umpire, the base coach at third base, or  first base, by touching or holding the runner, physically assists him  in returning to or leaving third base or first base. <br />
                      (j) With a runner on third base, the base coach leaves his box and acts in any manner to draw a throw by a fielder;<br />
                      (k) In running the last half of the distance from home base to first  base while the ball is being fielded to first base, he runs outside (to  the right of) the three foot line, or inside (to the left of) the foul  line and, in the umpire's judgment, interferes with the fielder taking  the throw at first base, or attempting to field a batted ball; The  lines marking the three foot lane are a part of that &quot;lane&quot; but the  interpretation to be made is that a runner is required to have both  feet within the three foot &quot;lane&quot; or on the lines marking the &quot;lane.&quot; <br />
                      (l) He fails to avoid a fielder who is attempting to field a batted  ball, or intentionally interferes with a thrown ball, provided that if  two or more fielders attempt to field a batted ball, and the runner  comes in contact with one or more of them, the umpire shall determine  which fielder is entitled to the benefit of this rule, and shall not  declare the runner out for coming in contact with a fielder other than  the one the umpire determines to be entitled to field such a ball; When  a catcher and batter runner going to first base have contact when the  catcher is fielding the ball, there is generally no violation and  nothing should be called. &quot;Obstruction&quot; by a fielder attempting to  field a ball should be called only in very flagrant and violent cases  because the rules give him the right of way, but of course such &quot;right  of way&quot; is not a license to, for example, intentionally trip a runner  even though fielding the ball. If the catcher is fielding the ball and  the first baseman or pitcher obstructs a runner going to first base  &quot;obstruction&quot; shall be called and the base runner awarded first base.<br />
                      (m) A fair ball touches him on fair territory before touching a  fielder. If a fair ball goes through, or by, an infielder, and touches  a runner immediately back of him, or touches the runner after having  been deflected by a fielder, the umpire shall not declare the runner  out for being touched by a batted ball. In making such decision the  umpire must be convinced that the ball passed through, or by, the  fielder, and that no other infielder had the chance to make a play on  the ball. If, in the judgment of the umpire, the runner deliberately  and intentionally kicks such a batted ball on which the infielder has  missed a play, then the runner shall be called out for interference. <br />
                      PENALTY FOR INTERFERENCE: The runner is out and the ball is dead.<br />
                      <br />
                      <strong>7.10</strong><br />
                      Any runner shall be called out, on appeal, when_<br />
                      <br />
                      (a) After a fly ball is caught, he fails to retouch his original  base before he or his original base is tagged; &quot;Retouch,&quot; in this rule,  means to tag up and start from a contact with the base after the ball  is caught. A runner is not permitted to take a flying start from a  position in back of his base. <br />
                      (b) With the ball in play, while advancing or returning to a base, he  fails to touch each base in order before he, or a missed base, is  tagged.<br />
                      <br />
                      <strong>APPROVED RULING: </strong><br />
                      (1) No runner may return to touch a missed base after a following runner has scored. <br />
                      (2) When the ball is dead, no runner may return to touch a missed base  or one he has left after he has advanced to and touched a base beyond  the missed base.<br />
                      <br />
                      <strong>PLAY.</strong> (a) Batter hits ball out of park or ground rule  double and misses first base (ball is dead)_he may return to first base  to correct his mistake before he touches second but if he touches  second he may not return to first and if defensive team appeals he is  declared out at first.<br />
                      <br />
                      <strong>PLAY.</strong> (b) Batter hits ball to shortstop who throws  wild into stand (ball is dead)_batter runner misses first base but is  awarded second base on the overthrow. Even though the umpire has  awarded the runner second base on the overthrow, the runner must touch  first base before he proceeds to second base. These are appeal plays.<br />
                      <br />
                      (c) He overruns or overslides first base and fails to return to the base immediately, and he or the base is tagged;<br />
                      (d) He fails to touch home base and makes no attempt to return to that  base, and home base is tagged. Any appeal under this rule must be made  before the next pitch, or any play or attempted play. If the violation  occurs during a play which ends a half inning, the appeal must be made  before the defensive team leaves the field. An appeal is not to be  interpreted as a play or an attempted play. Successive appeals may not  be made on a runner at the same base. If the defensive team on its  first appeal errs, a request for a second appeal on the same runner at  the same base shall not be allowed by the umpire. (Intended meaning of  the word &quot;err&quot; is that the defensive team in making an appeal threw the  ball out of play. For example, if the pitcher threw to first base to  appeal and threw the ball into the stands, no second appeal would be  allowed.) Appeal plays may require an umpire to recognize an apparent  &quot;fourth out.&quot; If the third out is made during a play in which an appeal  play is sustained on another runner, the appeal play decision takes  precedence in determining the out. If there is more than one appeal  during a play that ends a half inning, the defense may elect to take  the out that gives it the advantage. For the purpose of this rule, the  defensive team has &quot;left the field&quot; when the pitcher and all infielders  have left fair territory on their way to the bench or clubhouse. If two  runners arrive at home base about the same time and the first runner  misses home plate but a second runner legally touches the plate, the  runner is tagged out on his attempt to come back and touch the base or  is called out, on appeal, then he shall be considered as having been  put out before the second runner scored and being the third out. Second  runner's run shall not count, as provided in Rule 7.12. If a pitcher  balks when making an appeal, such act shall be a play. An appeal should  be clearly intended as an appeal, either by a verbal request by the  player or an act that unmistakably indicates an appeal to the umpire. A  player, inadvertently stepping on the base with a ball in his hand,  would not constitute an appeal. Time is not out when an appeal is being  made. <br />
                      <br />
                      <strong>7.11</strong><br />
                      The players, coaches or any member of an  offensive team shall vacate any space (including both dugouts) needed  by a fielder who is attempting to field a batted or thrown ball. <br />
                      <strong> PENALTY:</strong> Interference shall be called and the batter or runner on whom the play is being made shall be declared out. <br />
                      <br />
                      <strong>7.12</strong><br />
                      Unless two are out, the status of a following runner is not affected by  a preceding runner's failure to touch or retouch a base. If, upon  appeal, the preceding runner is the third out, no runners following him  shall score. If such third out is the result of a force play, neither  preceding nor following runners shall score.
</p>

</div>
</div>
</div>

<footer>
<?php include('includes/footer.php');?>
</footer>

</div>
</body>
</html>